package io.lp0onfire.fireband;

public enum DamageType {
  DAMAGE_SLASHING,
  DAMAGE_PIERCING,
  DAMAGE_CRUSHING,
  DAMAGE_MANA,
  DAMAGE_ACID,
  DAMAGE_ELEC,
  DAMAGE_FIRE,
  DAMAGE_ICE,
  DAMAGE_WATER,
  DAMAGE_AIR,
  DAMAGE_EARTH,
  DAMAGE_POISON,
  DAMAGE_LIGHT,
  DAMAGE_DARK,
  DAMAGE_HOLY,
  DAMAGE_UNHOLY,
  DAMAGE_SOUND,
  DAMAGE_FORCE,
  DAMAGE_TIME
}