package io.lp0onfire.fireband;

public enum ItemType {
  TYPE_WEAPON,
  TYPE_ARMOUR_BODY,
  TYPE_ARMOUR_CLOAK,
  TYPE_ARMOUR_HANDS,
  TYPE_ARMOUR_HEAD,
  TYPE_ARMOUR_FEET,
  TYPE_ARMOUR_SHIELD,
  TYPE_ARMOUR_AMULET,
  TYPE_ARMOUR_RING,
  TYPE_SCROLL,
  TYPE_POTION,
  TYPE_ROD,
  TYPE_WAND,
  TYPE_STAFF,
}
